### ISSUE TITLE
Easier to read version?

### ISSUE THREAD

**Issue by mindctrl** [flexiblegs/flexiblegs-scss-plus#5]
`flexible.css` has lines that are over 7000 columns wide. It would be nice to have it formatted so it's easy to read.

Instead of this:
`.xs-18-9,.xs-20-10,.xs-24-12{width:50%;}.xs-3-1,.xs-6-2,.xs-12-4,.xs-15-5,.xs-21-7,.xs-24-8{width:33.333333333333336%;}`

Something like this:

``` .xs-18-9,
.xs-20-10,
.xs-24-12 {
  width:50%;
}

.xs-3-1,
.xs-6-2,
.xs-12-4,
.xs-15-5,
.xs-21-7,
.xs-24-8 {
  width:33.333333333333336%;
}
```

**Comment by dnomak** [comment]
thanks @mindctrl
